name: buld-repo
on: [push, pull_request]
jobs:
  building-server:
      runs-on: ${{ matrix.os }}
      env: 
        DATABASE_URL: sqlite:./rc_server.db
      strategy:
        matrix:
          os: [ubuntu-latest]
      steps: 
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
        - run: cargo install sqlx-cli
        - run: sqlx database create
        - run: sqlx migrate run --source ./server/migrations
        - name : Bulding app
          run: cargo build --release -p server
        - run: mkdir server_linux
        - run: cp -r ./server/migrations ./target/release/server ./server/.env.example ./server_linux
        - run: zip -r ./server_linux.zip ./server_linux
        - name: Archiving server
          uses: actions/upload-artifact@v4
          with:
            name: server-linux
            path: ./server_linux.zip
         
